### ISSUE TITLE
Analytics data is missing from create checkout request

### ISSUE THREAD

**Issue by jrummell** [mattgenious/RechargeSharp#11]
I might be missing something, but I can't find a way to include analytics data when creating a checkout.

Here's an excerpt from the API documentation:

> **utm_params** optional
> utm_params will be added to subscription, customer and charge objects after successful processing of the checkout.

https://developer.rechargepayments.com/v1#create-a-checkout

```json
{
  "analytics_data": {
    "utm_params": [{
      "utm_campaign": "spring_sale",
      "utm_content": "textlink",
      "utm_data_source": "shopify_cookie",
      "utm_medium": "cpc",
      "utm_source": "google",
      "utm_term": "mleko",
      "utm_timestamp": "2020-03-05"
    }]
  },
  "discount_code": "POPUS_25",
  "email":"somerandomemail@test.com",
  "..."
```

I'm happy to submit a pull request as we need this functionality to complete a Recharge integration for a client.

**Comment by mattgenious** [comment]
Hey @jrummell thank you, I'll review it and merge the pull request if it checks out :-) just a heads up by the way, it seems that 3d-secure and api checkouts that have a 100% discount has some issues with setup_intents, we have been forced to create a workaround using the onetimes endpoint for cases where the checkouts total price is 0 but I expect ReCharge to fix that soon.

**Comment by jrummell** [comment]
> Hey @jrummell thank you, I'll review it and merge the pull request if it checks out :-) just a heads up by the way, it seems that 3d-secure and api checkouts that have a 100% discount has some issues with setup_intents, we have been forced to create a workaround using the onetimes endpoint for cases where the checkouts total price is 0 but I expect ReCharge to fix that soon.

You're welcome. And thanks for the heads up!
